name: opengslenv
channels:
  - conda-forge
  - defaults
dependencies:
  - brotli-python=1.1.0=py38hd3f51b4_1
  - ca-certificates=2025.8.3=h4c7d964_0
  - idna=3.10=pyhd8ed1ab_0
  - libffi=3.4.4=hd77b12b_1
  - openssl=3.5.2=h725018a_0
  - pip=24.2=py38haa95532_0
  - pysocks=1.7.1=pyh0701188_6
  - python=3.8.20=h8205438_0
  - python_abi=3.8=2_cp38
  - setuptools=75.1.0=py38haa95532_0
  - sqlite=3.50.2=hda9a48d_1
  - ucrt=10.0.22621.0=haa95532_0
  - vc=14.3=h2df5915_10
  - vc14_runtime=14.44.35208=h4927774_10
  - vs2015_runtime=14.44.35208=ha6b5a95_10
  - wheel=0.44.0=py38haa95532_0
  - win_inet_pton=1.1.0=pyh7428d3b_7
  - pip:
    - alembic==1.14.1
    - certifi==2025.8.3
    - charset-normalizer==3.4.3
    - colorama==0.4.6
    - colorlog==6.9.0
    - dgl==0.9.0
    - filelock==3.16.1
    - fsspec==2025.3.0
    - googledrivedownloader==1.0.0
    - greenlet==3.1.1
    - importlib-metadata==8.5.0
    - importlib-resources==6.4.5
    - isodate==0.7.2
    - jinja2==3.1.6
    - joblib==1.4.2
    - llvmlite==0.41.1
    - mako==1.3.10
    - markupsafe==2.1.5
    - mpmath==1.3.0
    - networkx==3.1
    - numba==0.58.1
    - numpy==1.24.4
    - opt-einsum==3.4.0
    - optuna==4.5.0
    - packaging==25.0
    - pandas==2.0.3
    - psutil==7.0.0
    - pyparsing==3.1.4
    - pyro-api==0.1.2
    - pyro-ppl==1.8.0
    - python-dateutil==2.9.0.post0
    - python-louvain==0.16
    - pytz==2025.2
    - pyyaml==5.1.2
    - rdflib==7.1.4
    - requests==2.32.4
    - ruamel-yaml==0.18.15
    - ruamel-yaml-clib==0.2.8
    - scikit-learn==1.3.2
    - scipy==1.10.1
    - six==1.17.0
    - sqlalchemy==2.0.43
    - sympy==1.13.3
    - threadpoolctl==3.5.0
    - torch==1.9.1
    - torch-geometric==2.1.0
    - torch-scatter==2.0.9
    - torch-sparse==0.6.12
    - tqdm==4.67.1
    - typing-extensions==4.13.2
    - tzdata==2025.2
    - urllib3==2.2.3
    - zipp==3.20.2
prefix: C:\Users\11622563\Anaconda3\envs\opengslenv
